### ISSUE TITLE
Is there a hash pattern？

### ISSUE THREAD

**Issue by cyz1901** [tulz-app/frontroute#198]
Hey! I have a static SPA app in vercel using `frontrouteCalico` and `Calico`.
I found i trigger F5 reflash website will return 404.
I would like to inquire if there are any methods in this library that can implement functions similar to `react-router` hash history

**Comment by yurique** [comment]
Hey.

While hash routing is not provided out of the box, you can create a custom `LocationProvider` and tell frontroute to use it.

Here's how it might look like:

```scala

import frontroute._
import com.raquo.laminar.api.L._
import org.scalajs.dom

import scala.scalajs.js

class HashLocationProvider(
  popStateEvents: EventStream[dom.PopStateEvent]
) extends LocationProvider {

  private val currentVar = Var(Option.empty[Location])
  val current: Signal[Option[Location]] = currentVar.signal.distinct

  def start()(implicit owner: Owner): Subscription = {
    EventStream
      .merge(
        EventStream.fromValue(js.undefined: js.Any),
        popStateEvents.map(_.state),
      )
      .map { state =>
        Location(dom.window.location, state).copy(
          path = dom.window.location.hash.drop(1).split('/').filterNot(_.isEmpty).toList
        )
      }
      .foreach { l =>
        currentVar.set(Some(l))
      }
  }

}
```


Then, in your app, instead of `routes( ...myApp)` use the `initRouting` directive:

```scala
val myApp = 
  div(

    initRouting(new HashLocationProvider(windowEvents(_.onPopState))),

    pathEnd { div("index page") },
    path("some-page") { div("some page") }
  )
```

You'll need to manage your links and navigation manually, since `LinkHandler` does not work with hash routing.

Hope this helps.

**Comment by yurique** [comment]
I just noticed you're using `frontroute-calico`, in that case you can take this as the starting point: https://github.com/tulz-app/frontroute-calico/blob/feature/calico/modules/frontroute/src/main/scala/frontroute/LocationProvider.scala 

The important part here is this:
```scala
        Location(dom.window.location, state).copy(
          path = dom.window.location.hash.drop(1).split('/').filterNot(_.isEmpty).toList
        )
```

**Comment by cyz1901** [comment]
Thank you for your help! i will try.
